

class AbilitiesManager:
    def __init__(self):
        self.abilities = {
            "Barbarian": [
                {"name": "Rage", "description": "Enter a furious state increasing damage."},
                {"name": "Reckless Attack", "description": "Gain advantage on melee attacks but enemies have advantage on you."},
                {"name": "Danger Sense", "description": "Advantage on Dexterity saves against visible effects."},
                {"name": "Feral Instinct", "description": "Advantage on initiative rolls."},
                {"name": "Brutal Critical", "description": "Extra damage dice on critical hits."},
                {"name": "Relentless Rage", "description": "Remain conscious when you would normally fall."},
                {"name": "Persistent Rage", "description": "Rage only ends if you fall unconscious or choose to stop."},
                {"name": "Indomitable Might", "description": "Use your strength score if it’s higher than a roll."},
                {"name": "Primal Champion", "description": "Increase strength and constitution scores by 4."},
                {"name": "Totem Spirit", "description": "Choose a totem for unique abilities."},
                {"name": "Fast Movement", "description": "Increase speed by 10 feet without heavy armor."},
                {"name": "Mindless Rage", "description": "Cannot be charmed or frightened while raging."},
                {"name": "Feral Charge", "description": "Dash and make a melee attack."},
                {"name": "Intimidating Presence", "description": "Frighten foes with your presence."},
                {"name": "Juggernaut", "description": "Push enemies back when hitting with melee attacks."},
                {"name": "Unstoppable", "description": "Resist all damage except psychic while raging."},
                {"name": "Earthshaker", "description": "Stomp to knock enemies prone."},
                {"name": "Titan’s Strength", "description": "Bonus to damage rolls with strength weapons."},
                {"name": "Savage Attacks", "description": "Double damage dice on critical hits."},
                {"name": "Primal Fury", "description": "Attack twice instead of once when taking the Attack action."}
            ],

            "Rogue": [
                {"name": "Sneak Attack", "description": "Deal extra damage with advantage or ally nearby."},
                {"name": "Cunning Action", "description": "Bonus action to Dash, Disengage, or Hide."},
                {"name": "Uncanny Dodge", "description": "Halve damage from attacker you can see."},
                {"name": "Evasion", "description": "No damage on Dexterity save success, half on failure."},
                {"name": "Reliable Talent", "description": "Treat rolls below 10 as 10 for proficient skills."},
                {"name": "Blindsense", "description": "Detect hidden or invisible creatures nearby."},
                {"name": "Slippery Mind", "description": "Gain proficiency in Wisdom saves."},
                {"name": "Elusive", "description": "No attack roll has advantage against you."},
                {"name": "Stroke of Luck", "description": "Turn missed attack into hit once per rest."},
                {"name": "Thief’s Reflexes", "description": "Take two turns in the first combat round."},
                {"name": "Fast Hands", "description": "Bonus action to use objects or tools."},
                {"name": "Second-Story Work", "description": "Climb faster and jump farther."},
                {"name": "Use Magic Device", "description": "Ignore magic item restrictions."},
                {"name": "Ambush Master", "description": "Advantage on initiative and first attack."},
                {"name": "Infiltration Expertise", "description": "Create false identities."},
                {"name": "Impostor", "description": "Mimic speech and behavior flawlessly."},
                {"name": "Poison Master", "description": "Resistance to poison and poison crafting."},
                {"name": "Master of Shadows", "description": "Become invisible in dim light/darkness."},
                {"name": "Slayer", "description": "Extra damage to creatures you've wounded."},
                {"name": "Elusive Target", "description": "Avoid opportunity attacks when moving away."}
            ],

            "Ranger": [
                {"name": "Favored Enemy", "description": "Deal extra damage to favored creature types."},
                {"name": "Natural Explorer", "description": "Benefit from favored terrain features."},
                {"name": "Fighting Style", "description": "Gain a special combat style bonus."},
                {"name": "Spellcasting", "description": "Cast ranger spells."},
                {"name": "Primeval Awareness", "description": "Detect nearby aberrations, dragons, or undead."},
                {"name": "Extra Attack", "description": "Attack twice instead of once."},
                {"name": "Land’s Stride", "description": "Move through difficult terrain without penalty."},
                {"name": "Hide in Plain Sight", "description": "Camouflage yourself in natural surroundings."},
                {"name": "Vanish", "description": "Hide as a bonus action."},
                {"name": "Feral Senses", "description": "Detect invisible creatures by hearing or smell."},
                {"name": "Foe Slayer", "description": "Add Wisdom modifier to damage against favored foes."},
                {"name": "Ambush Master", "description": "Gain advantage on attack rolls against surprised creatures."},
                {"name": "Deft Explorer", "description": "Increased speed and better travel efficiency."},
                {"name": "Hunter’s Defense", "description": "Choose defensive options like Evasion."},
                {"name": "Camouflage", "description": "Blend perfectly in natural environments."},
                {"name": "Relentless Tracker", "description": "Never lose track of your quarry."},
                {"name": "Beast Master Bond", "description": "Form a powerful bond with a beast companion."},
                {"name": "Greater Favored Enemy", "description": "Choose additional favored enemy types."},
                {"name": "Nature’s Wrath", "description": "Harness nature to restrain enemies."},
                {"name": "Survivor’s Instinct", "description": "Heal yourself quickly in wilderness."}
            ],

            "Wizard": [
                {"name": "Spellcasting", "description": "Cast wizard spells."},
                {"name": "Arcane Recovery", "description": "Recover spell slots during a short rest."},
                {"name": "Arcane Tradition", "description": "Choose a school of magic specialization."},
                {"name": "Spell Mastery", "description": "Cast certain low-level spells without slots."},
                {"name": "Signature Spells", "description": "Select powerful spells always prepared."},
                {"name": "Spell Resistance", "description": "Gain advantage on saving throws vs spells."},
                {"name": "Empowered Evocation", "description": "Add intelligence modifier to evocation damage."},
                {"name": "Potent Cantrip", "description": "Add damage to cantrips even on failed saves."},
                {"name": "Overchannel", "description": "Maximize damage for a spell at a cost."},
                {"name": "Improved Minor Illusion", "description": "Create sound and image illusions."},
                {"name": "Master of Magic", "description": "Reduce spell costs and improve casting."},
                {"name": "Sculpt Spells", "description": "Protect allies from evocation spells."},
                {"name": "Metamagic Adept", "description": "Alter spells with metamagic options."},
                {"name": "Spell Thief", "description": "Steal spells from other casters."},
                {"name": "Arcane Eye", "description": "Create an invisible magical eye for scouting."},
                {"name": "Counterspell", "description": "Interrupt another spellcaster's spell."},
                {"name": "Dispel Magic", "description": "End ongoing spells on others."},
                {"name": "Time Stop", "description": "Stop time briefly to act without interruption."},
                {"name": "Wish", "description": "Cast the most powerful spell in existence."},
                {"name": "Archmage", "description": "Reach the peak of arcane mastery."}
            ],

            "Sorcerer": [
                {"name": "Spellcasting", "description": "Cast sorcerer spells."},
                {"name": "Sorcerous Origin", "description": "Choose a magical bloodline or power source."},
                {"name": "Font of Magic", "description": "Convert sorcery points to spell slots."},
                {"name": "Metamagic", "description": "Modify spells with special effects."},
                {"name": "Flexible Casting", "description": "Convert sorcery points to spells flexibly."},
                {"name": "Quickened Spell", "description": "Cast spells as a bonus action."},
                {"name": "Twinned Spell", "description": "Target a second creature with a spell."},
                {"name": "Subtle Spell", "description": "Cast without verbal or somatic components."},
                {"name": "Empowered Spell", "description": "Reroll damage dice for spells."},
                {"name": "Heightened Spell", "description": "Give disadvantage on saving throws."},
                {"name": "Distant Spell", "description": "Double range of spells."},
                {"name": "Careful Spell", "description": "Protect some creatures from spell damage."},
                {"name": "Spell Bombardment", "description": "Extra damage on spells that hit multiple targets."},
                {"name": "Sorcery Surge", "description": "Bonus damage on spells."},
                {"name": "Bloodline Resilience", "description": "Gain resistance to damage."},
                {"name": "Draconic Presence", "description": "Frighten creatures around you."},
                {"name": "Elemental Affinity", "description": "Add charisma bonus to elemental spell damage."},
                {"name": "Dragon Wings", "description": "Grow wings and fly."},
                {"name": "Phoenix Soul", "description": "Resurrect self once per day."},
                {"name": "Sorcerous Restoration", "description": "Regain sorcery points on short rest."}
            ],

            "Druid": [
                {"name": "Druidic", "description": "Secret language of druids."},
                {"name": "Spellcasting", "description": "Cast druid spells."},
                {"name": "Wild Shape", "description": "Transform into animals."},
                {"name": "Circle Forms", "description": "Enhanced wild shape forms."},
                {"name": "Combat Wild Shape", "description": "Wild shape as a bonus action."},
                {"name": "Primal Strike", "description": "Wild shape attacks count as magical."},
                {"name": "Timeless Body", "description": "Slow aging and no need to eat or drink."},
                {"name": "Beast Spells", "description": "Cast spells while wild shaped."},
                {"name": "Archdruid", "description": "Use wild shape an unlimited number of times."},
                {"name": "Nature’s Ward", "description": "Immunity to poison and disease."},
                {"name": "Land’s Stride", "description": "Move through natural terrain without penalty."},
                {"name": "Nature’s Sanctuary", "description": "Protect animals and plants."},
                {"name": "Elemental Affinity", "description": "Resistance to elemental damage."},
                {"name": "Call Lightning", "description": "Summon a lightning storm."},
                {"name": "Earthbind", "description": "Hold flying creatures to the ground."},
                {"name": "Flame Blade", "description": "Create a fiery sword."},
                {"name": "Healing Touch", "description": "Heal wounds with a touch."},
                {"name": "Storm’s Fury", "description": "Control storms and weather."},
                {"name": "Wild Companion", "description": "Summon an animal ally."},
                {"name": "Spirit Walker", "description": "Communicate with spirits and ancestors."}
            ],

            "Paladin": [
                {"name": "Divine Sense", "description": "Detect good and evil."},
                {"name": "Lay on Hands", "description": "Heal wounds with a touch."},
                {"name": "Divine Smite", "description": "Deal extra radiant damage on hits."},
                {"name": "Sacred Oath", "description": "Choose an oath to follow."},
                {"name": "Aura of Protection", "description": "Add charisma bonus to saves."},
                {"name": "Aura of Courage", "description": "Allies can’t be frightened."},
                {"name": "Improved Divine Smite", "description": "Deal extra damage on all melee attacks."},
                {"name": "Cleansing Touch", "description": "End spells on self or others."},
                {"name": "Aura of Devotion", "description": "Allies can't be charmed."},
                {"name": "Purity of Spirit", "description": "Immunity to disease."},
                {"name": "Aura of Warding", "description": "Resistance to spell damage."},
                {"name": "Divine Intervention", "description": "Call on your deity for aid."},
                {"name": "Improved Lay on Hands", "description": "Increase healing pool."},
                {"name": "Extra Attack", "description": "Attack twice instead of once."},
                {"name": "Sacred Weapon", "description": "Add charisma bonus to attack rolls."},
                {"name": "Blinding Smite", "description": "Smite that blinds your enemy."},
                {"name": "Stunning Smite", "description": "Smite that stuns your enemy."},
                {"name": "Wrath of the Righteous", "description": "Deal extra damage to fiends and undead."},
                {"name": "Aura of Vitality", "description": "Heal allies in your aura."},
                {"name": "Holy Avenger", "description": "Wield a powerful magic weapon."}
            ],

            "Bard": [
                {"name": "Spellcasting", "description": "Cast bard spells."},
                {"name": "Bardic Inspiration", "description": "Grant bonuses to allies."},
                {"name": "Jack of All Trades", "description": "Add half proficiency to any skill."},
                {"name": "Song of Rest", "description": "Heal allies during short rests."},
                {"name": "Expertise", "description": "Double proficiency bonus in selected skills."},
                {"name": "Countercharm", "description": "Grant advantage on saves against fear and charm."},
                {"name": "Magical Secrets", "description": "Learn spells from other classes."},
                {"name": "Superior Inspiration", "description": "Regain Bardic Inspiration on crit."},
                {"name": "College Feature", "description": "Gain special abilities from bard colleges."},
                {"name": "Enthralling Performance", "description": "Charm audience with performance."},
                {"name": "Additional Magical Secrets", "description": "Learn even more spells."},
                {"name": "Improved Bardic Inspiration", "description": "Bardic Inspiration die increases."},
                {"name": "Font of Inspiration", "description": "Regain all Bardic Inspiration dice on rest."},
                {"name": "Superior Performance", "description": "Increased performance effectiveness."},
                {"name": "Spell Mastery", "description": "Cast certain spells without slots."},
                {"name": "Fascinate", "description": "Captivate multiple creatures."},
                {"name": "Inspire Courage", "description": "Increase allies’ attack and damage."},
                {"name": "Dazzling Display", "description": "Stun enemies with your performance."},
                {"name": "Master of Song", "description": "Ultimate bardic performance."},
                {"name": "Soulful Melody", "description": "Heal and inspire with song."}
            ],

            "Cleric": [
                {"name": "Divine Domain", "description": "Choose a domain granting unique powers."},
                {"name": "Spellcasting", "description": "Cast cleric spells."},
                {"name": "Channel Divinity", "description": "Turn undead or fuel domain powers."},
                {"name": "Divine Intervention", "description": "Call on your deity for aid."},
                {"name": "Divine Strike", "description": "Add extra damage to weapon attacks."},
                {"name": "Blessing of the Gods", "description": "Grant blessings to allies."},
                {"name": "Turn Undead", "description": "Force undead to flee."},
                {"name": "Destroy Undead", "description": "Destroy weaker undead."},
                {"name": "Potent Spellcasting", "description": "Add Wisdom modifier to cleric spell damage."},
                {"name": "Improved Channel Divinity", "description": "Gain additional Channel Divinity uses."},
                {"name": "Divine Favor", "description": "Increase attack rolls and damage."},
                {"name": "Aura of Protection", "description": "Add charisma bonus to saving throws."},
                {"name": "Guardian Spirit", "description": "Protect allies from harm."},
                {"name": "Divine Resilience", "description": "Gain resistance to damage types."},
                {"name": "Sacred Shield", "description": "Create shields that absorb damage."},
                {"name": "Healing Touch", "description": "Restore health to allies."},
                {"name": "Blessed Healer", "description": "Heal yourself when healing others."},
                {"name": "Radiant Soul", "description": "Glow with radiant energy."},
                {"name": "Spirit Guardians", "description": "Call spirits to protect you."},
                {"name": "Holy Avenger", "description": "Wield holy power to smite evil."}
            ],
        }

    def get_abilities_by_class_and_level(self, char_class, level):
        class_abilities = self.abilities.get(char_class, [])
        return class_abilities[:level]
